function model_stage = do_proposal_train(conf, model_stage, do_val)
global dataset

model_stage.output_model_file = proposal_train(conf, ...
                                'do_val',           do_val, ...
                                'solver_def_file',  model_stage.solver_def_file, ...
                                'net_file',         model_stage.init_net_file, ...
                                'cache_name',       model_stage.cache_name, ...
                                'snapshot',         model_stage.snapshot);
end
